<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bistumsliga"
 *
 * Auto generated by Extension Builder 2021-11-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'bistumsliga',
    'description' => 'Customization extension for bistumsliga.de',
    'category' => 'templates',
    'author' => 'Jakob Berlin',
    'author_email' => 'jakob@ybals.de',
    'state' => 'beta',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-12.4.99',
            'cfc_league' => '>= 1.7.1'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'psr-4' => [
            'Bistumsliga\\Bistumsliga\\' => 'Classes'
        ]
    ],
];
